### ISSUE TITLE
Test with WSL 1 on Windows

### ISSUE THREAD

**Issue by lptr** [gradle/native-platform#188]
## Conclusions

WSL 1 seems to be working fine mostly:

- Recognizes the operating system as Linux/AMD64 (tested on Ubuntu 20.04 w/ Windows 10/1909)
- We can't _build_ `native-platform`: the build finishes, but there are no native libraries
- Removing the parent directory is not reported properly sometimes (see build scan for details)

Build scan: https://ge.gradle.org/s/ewo2aroynlg4y

For WSL 2 see https://github.com/gradle/native-platform/issues/250.

----
/cc @gradle/execution

**Comment by lptr** [comment]
This is weird. I've installed WSL1 with Ubuntu 20.04, and tried to build `native-platform`. The strange thing is that the build itself uses file watching perfectly (using Gradle 6.5.1):

```bash
lptr@windows45:~/Workspace/native-platform$ ./gradlew :test
Watching the file system is an incubating feature.
Received 0 file system events since last build
Virtual file system retained information about 194 files, 19 directories and 2 missing files since last build
Dependency verification is an incubating feature.

...

Received 3 file system events for current build
Virtual file system retains information about 783 files, 82 directories and 5 missing files till next build
```

But all the file-watching tests fail because of a library loading problem:

```text
net.rubygrapefruit.platform.NativeIntegrationUnavailableException: Native library 'libnative-platform-file-events.so' is not available for Linux amd64.	
    at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:63)	
    at net.rubygrapefruit.platform.internal.Platform.initFileEventFunctions(Platform.java:143)	
    at net.rubygrapefruit.platform.internal.Platform$Linux.get(Platform.java:295)	
    at net.rubygrapefruit.platform.Native.get(Native.java:88)
```

**Comment by lptr** [comment]
I thought maybe things worked with 0.22-milestone-3 (the version used by the wrapper), but checking out that tag and running `./gradlew :test` I get the same exceptions.

**Comment by lptr** [comment]
We are clearly running a Linux file system watcher scheme:

```bash
lptr@windows45:~/Workspace/native-platform$ ./gradlew --version

------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8 (Ubuntu 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OS:           Linux 4.4.0-18362-Microsoft amd64
```

This is from `./gradlew clean assemble --debug | tee build.log`:

```log
2020-08-03T22:18:58.262+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Processing 32 bytes worth of events                                                                                                                                                                                             2020-08-03T22:18:58.262+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Event mask: 0x2 for build.log (wd = 32, cookie = 0x0, len = 16)
2020-08-03T22:18:58.264+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Processed 1 events
2020-08-03T22:18:58.268+0200 [DEBUG] [org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem] Handling VFS change MODIFIED /home/lptr/Workspace/native-platform/build.log                                                                                                                                              2020-08-03T22:18:58.276+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Processing 32 bytes worth of events                                                                                                                                                                                             2020-08-03T22:18:58.279+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Event mask: 0x2 for build.log (wd = 32, cookie = 0x0, len = 16)                                                                                                                                                                 2020-08-03T22:18:58.279+0200 [DEBUG] [org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem] Handling VFS change MODIFIED /home/lptr/Workspace/native-platform/build.log
2020-08-03T22:18:58.279+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Processed 1 events                                                                                                                                                                                                              2020-08-03T22:18:58.282+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Processing 16 bytes worth of events                                                                                                                                                                                             2020-08-03T22:18:58.283+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Event mask: 0x8000 for  (wd = 32, cookie = 0x0, len = 0)
2020-08-03T22:18:58.283+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Finished watching recently unregistered watch point '/home/lptr/Workspace/native-platform' (wd = 32)                                                                                                                            2020-08-03T22:18:58.283+0200 [DEBUG] [net.rubygrapefruit.platform.internal.jni.NativeLogger] Processed 1 events                                                                        
```

It is clearly using Linux file watching with watch descriptors (`wd`) etc.

**Comment by lptr** [comment]
OK, it seems that the build itself does not recognize the operating system, and thus doesn't build the relevant platform, and we end up with a `native-platform.jar` that has no native libraries embedded in them.

But the feature seems to work fine as it is.

**Comment by lptr** [comment]
@wolfs how can I populate the `incoming-repo` directory so that I can run `./gradlew :test -PtestVersionFromLocalRepository`?

**Comment by wolfs** [comment]
@lptr You can use a released version from jCenter() instead of populating `incoming-repo`. I would need to figure out what you need to do to accomplish this.
