### ISSUE TITLE
Some logging (?) causes `wstring_convert::to_bytes` native exception

### ISSUE THREAD

**Issue by wolfs** [gradle/native-platform#215]
When upgrading the latest native platform `master`, we get some exceptions:

```
Error while receiving file changes
net.rubygrapefruit.platform.NativeException: wstring_convert::to_bytes
  at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.executeRunLoop0(Native Method)
  at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.access$100(AbstractFileEventFunctions.java:156)
  at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher$1.run(AbstractFileEventFunctions.java:169)
```

I suppose we log something wrong: See https://builds.gradle.org/buildConfiguration/Gradle_Check_VfsRetention_28_bucket18/34945427?

**Comment by wolfs** [comment]
Two more builds failed with the same error message:
- https://builds.gradle.org/buildConfiguration/Gradle_Check_VfsRetention_28_bucket15/34945424
- https://builds.gradle.org/buildConfiguration/Gradle_Check_VfsRetention_28_bucket22/34945431

All three failures happened on EC2 agents at roughly the same time.

**Comment by lptr** [comment]
Looks like the only culprit is this commit, but I still cannot reproduce the problem with `native-platform` only: https://github.com/gradle/native-platform/commit/cbc5429b4ace97d12a0212860d876eca95cb3924

**Comment by lptr** [comment]
OK, I think I found it...
