### ISSUE TITLE
Check file system watching support on Windows ReFS

### ISSUE THREAD

**Issue by lptr** [gradle/native-platform#253]
---
cc: @gradle/execution

**Comment by sschuberth** [comment]
With Windows 11 and a ReFS DevDrive, Gradle 8.4 gives me:

```
$ ./gradlew :plugins:commands:dependencies
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
Error while receiving file changes
net.rubygrapefruit.platform.NativeException: Error received when handling events, error = 1: D:\GitHub\oss-review-toolkit\ort
        at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.executeRunLoop0(Native Method)
        at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.executeRunLoop(AbstractNativeFileEventFunctions.java:42)
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$AbstractFileWatcher$1.run(AbstractFileEventFunctions.java:154)
Stopping file watching and invalidating VFS after an error happened
```

So I guess there are still problems.
