### ISSUE TITLE
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'BuildInfo'./Caused by: java.lang.IllegalStateException: GradleProperties has not been loaded yet.

### ISSUE THREAD

**Issue by akar1492** [gradle/native-platform#302]
Using Gradle 6.8.1 and springboot 2.6.2.
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'BuildInfo'.
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:97)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:84)
	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:452)
	at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:202)
	at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:84)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.create(AnnotationProcessingTaskFactory.java:48)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.createTask(DefaultTaskContainer.java:326)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.access$200(DefaultTaskContainer.java:77)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.createDomainObject(DefaultTaskContainer.java:701)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.createDomainObject(DefaultTaskContainer.java:658)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:941)
	... 19 more
Caused by: java.lang.IllegalStateException: GradleProperties has not been loaded yet.
	at org.gradle.initialization.DefaultGradlePropertiesController$NotLoaded.gradleProperties(DefaultGradlePropertiesController.java:80)
	at org.gradle.initialization.DefaultGradlePropertiesController$SharedGradleProperties.gradleProperties(DefaultGradlePropertiesController.java:63)
	at org.gradle.initialization.DefaultGradlePropertiesController$SharedGradleProperties.find(DefaultGradlePropertiesController.java:54)
	at org.gradle.api.internal.provider.sources.GradlePropertyValueSource.obtain(GradlePropertyValueSource.java:36)
	at org.gradle.api.internal.provider.sources.GradlePropertyValueSource.obtain(GradlePropertyValueSource.java:24)
	at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.lambda$obtainValueForThe1stTime$0(DefaultValueSourceProviderFactory.java:344)
	at org.gradle.internal.Try.ofFailable(Try.java:39)
	at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.obtainValueForThe1stTime(DefaultValueSourceProviderFactory.java:344)
	at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.obtain(DefaultValueSourceProviderFactory.java:333)
	at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$ValueSourceProvider.calculateOwnValue(DefaultValueSourceProviderFactory.java:299)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:93)
	at org.springframework.boot.gradle.tasks.buildinfo.BuildInfoProperties.projectVersion(BuildInfoProperties.java:72)
	at org.springframework.boot.gradle.tasks.buildinfo.BuildInfoProperties.<init>(BuildInfoProperties.java:63)
	at org.springframework.boot.gradle.tasks.buildinfo.BuildInfo.<init>(BuildInfo.java:46)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1969)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:468)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:90)

**Comment by ov7a** [comment]
Sorry for the late reply.

Given that Gradle 6 is EOL (and Spring Boot 2.6.2 too), closing this as obsolete. Please open a new issue with the latest versions of them if you still experience the problem.
